#!/usr/bin/env python3
"""Validate a paper-interpretation Markdown output against captions.json.

The checks are intentionally mechanical:
- every extracted Figure/Table image is referenced in Markdown;
- every Figure/Table has a caption-translation marker and grounding note;
- relative image paths resolve from the Markdown file;
- paragraph-count markers, when present, match;
- obvious PDF text-extraction artifacts are absent from the final output.

This is not a semantic translation judge. It is a guardrail that catches the
common failures that are expensive to notice by hand at the end.
"""

import argparse
import json
import re
import sys
from pathlib import Path


FORBIDDEN_TEMPLATE_HEADINGS = [
    "一句话总结",
    "为什么读这篇",
    "关键观察",
    "核心主张",
    "全文翻译与论文解读",
    "章节总结",
]


BAD_TEXT_ARTIFACTS = [
    ("page_marker", re.compile(r"=== Page \d+ ===")),
    ("nul_byte", re.compile("\x00")),
    ("pdf_hyphen_linebreak", re.compile(r"[A-Za-z]{3,}-\n[A-Za-z]{3,}")),
]


BAD_MATH_ARTIFACTS = [
    ("quadratic_attention_lost_superscript", re.compile(r"O\(L2\)")),
    ("tau_squared_lost_superscript", re.compile(r"τ\s+2-Bench")),
    ("summation_symbol_broken_gx", re.compile(r"(?m)^\s*G\s*\n\s*X\s*$")),
    ("summation_symbol_broken_len_y", re.compile(r"(?m)^\s*\|y_i\|\s*\n\s*X\s*$")),
    ("matrix_superscript_broken", re.compile(r"\bW\s+U[QKV]\b")),
]


PARA_MARKER_RE = re.compile(
    r"<!--\s*source-paragraphs:\s*(\d+)\s*;\s*translated-paragraphs:\s*(\d+)\s*-->",
    re.IGNORECASE,
)


IMAGE_RE = re.compile(r"!\[[^\]]*\]\(([^)]+)\)")


def strip_code_blocks(text: str) -> str:
    return re.sub(r"```.*?```", "", text, flags=re.DOTALL)


def is_allowed_extra_image(path: Path) -> bool:
    """Images generated by this workflow that are not Figure/Table manifest items."""
    return path.name == "contact_sheet.png" or path.name.startswith("equation_")


def caption_marker_pattern(fig_id: str) -> re.Pattern:
    return re.compile(
        r"\*\*\s*"
        + re.escape(fig_id)
        + r"\s+caption\s+(?:中文)?翻译\s*\*\*\s*[:：]",
        re.IGNORECASE,
    )


def find_caption_marker(text: str, fig_id: str):
    return caption_marker_pattern(fig_id).search(text)


def has_grounding_near(text: str, start: int, window: int = 1200) -> bool:
    snippet = text[start : start + window]
    return bool(re.search(r"\*\*[^*\n]*(?:Grounding note|视觉校验|表格 Grounding note)[^*\n]*\*\*\s*[:：]", snippet))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--markdown", required=True, help="Markdown output to validate")
    ap.add_argument("--captions", required=True, help="captions.json from extract_figures.py")
    ap.add_argument(
        "--allow-template-terms",
        action="store_true",
        help="Allow old summary-template terms, for meta self-test reports only",
    )
    args = ap.parse_args()

    md_path = Path(args.markdown)
    captions_path = Path(args.captions)
    text = md_path.read_text(encoding="utf-8")
    text_no_code = strip_code_blocks(text)
    data = json.loads(captions_path.read_text(encoding="utf-8"))
    figures = data.get("figures", [])

    errors = []
    warnings = []

    # Image path coverage.
    refs = IMAGE_RE.findall(text)
    resolved_refs = []
    for ref in refs:
        # Ignore URLs.
        if re.match(r"^[a-z]+://", ref):
            continue
        ref_path = Path(ref)
        full = ref_path if ref_path.is_absolute() else (md_path.parent / ref_path)
        resolved_refs.append((ref, full))
        if not full.exists():
            errors.append(f"missing image path: {ref}")

    ref_filenames = {full.name for _, full in resolved_refs}
    expected_filenames = {fig.get("filename") for fig in figures if fig.get("filename")}
    missing_images = sorted(expected_filenames - ref_filenames)
    extra_manifestless = sorted(
        p.name for _, p in resolved_refs
        if p.name not in expected_filenames and not is_allowed_extra_image(p)
    )
    if missing_images:
        errors.append(f"missing manifest images in markdown: {', '.join(missing_images)}")
    if extra_manifestless:
        warnings.append(f"markdown references images not in manifest: {', '.join(extra_manifestless)}")

    # Caption and grounding coverage.
    for fig in figures:
        fig_id = fig.get("id", "")
        if not fig_id:
            continue
        marker = find_caption_marker(text, fig_id)
        if not marker:
            errors.append(f"missing caption translation marker: {fig_id}")
            continue
        if not has_grounding_near(text, marker.end()):
            errors.append(f"missing grounding note near caption: {fig_id}")

    # Paragraph count markers.
    markers = PARA_MARKER_RE.findall(text)
    if not markers:
        warnings.append("no paragraph-count markers found")
    for idx, (src, dst) in enumerate(markers, 1):
        if int(src) != int(dst):
            errors.append(f"paragraph marker {idx} mismatch: source={src}, translated={dst}")

    if "全文理解依据" not in text and "global-context" not in text and "paper_global_context" not in text:
        warnings.append("no full-paper context marker found")

    # Old summary-template markers in final translation output.
    if not args.allow_template_terms:
        for term in FORBIDDEN_TEMPLATE_HEADINGS:
            if term in text_no_code:
                errors.append(f"forbidden summary-template term present: {term}")

    # Raw PDF extraction artifacts and math artifacts.
    for name, pattern in BAD_TEXT_ARTIFACTS:
        if pattern.search(text_no_code):
            errors.append(f"text extraction artifact present: {name}")
    for name, pattern in BAD_MATH_ARTIFACTS:
        if pattern.search(text_no_code):
            errors.append(f"math extraction artifact present: {name}")

    print(f"figures_in_manifest={len(figures)}")
    print(f"image_refs={len(refs)}")
    print(f"caption_markers={sum(1 for fig in figures if find_caption_marker(text, fig.get('id', '')))}")
    print(f"paragraph_markers={len(markers)}")
    if warnings:
        print("WARNINGS:")
        for w in warnings:
            print(f"  - {w}")
    if errors:
        print("ERRORS:")
        for e in errors:
            print(f"  - {e}")
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
